config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index' ,as: 'home'
  get "/about", to: "pages#about" ,as:'about'

  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :manage , Post , author_id: user.id
         can :manage , Comment , author_id: user.id
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments ,:dependent => :destroy
validates :title , presence: true,
                    length: {minimum:5,
                            maximum:50}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def create
    @post=Post.find(params[:post_id])
    @comment =@post.comments.new(comment_params)
    @comment.author_id = current_user.id
    @comment.save

    redirect_to post_path(@post)
      
  end
  private def comment_params
    params.require(:comment).permit(:username,:body)
    end

  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title='About Us';
        @Desc='Mego el gamd awi b fadl allah ';
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    load_and_authorize_resource
     def index
    @posts=Post.all
    end

    def new 
        @post =Post.new
    end


    def show
        @post=Post.find(params[:id])
    end

   

    def create
       # render plain:params[:post].inspect
       #@post = Post.new(post_params)
       @post=Post.new(post_params)
       @post.author_id = current_user.id
      if(@post.save)
       redirect_to @post
      else
        render 'new'
      end
    end
    private def post_params
    params.require(:post).permit(:title,:body)
    end


    def edit
    @post=Post.find(params[:id])
    end

    def update
        @post=Post.find(params[:id])

        if(@post.update(post_params))
            redirect_to @post
        else
          render 'edit'
        end

    end


def destroy
   
    @post=Post.find(params[:id])
    
     @post.destroy
    redirect_to posts_path
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>

    <div class="card">
        <h5 class="card-header">
            <%= comment.username  %>
        </h5>
        <div class="card-body">
            <p class="card-text">
                <%= comment.body  %>
            </p>
        </div>
    </div>

    <% end %>

app/views/comments/_form.html.erb
<h3>
    Add Comment</h3>
<%= form_for ([@post,@post.comments.build]) do |f| %>

    <p>

        <%= f.label :username %>
            <%= f.text_field(:username,{:class=>'form-control'}) %>

    </p>
    <p>

        <%= f.label :body %>
            <%= f.text_field(:body,{:class=>'form-control'}) %>

    </p>

    <p>
        <%= f.submit({:class=>'btn btn-primary'}) %>
    </p>

    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

            <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'%>
                <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to  "home", home_path %>
                </li>
            </ul>
        </div>
        <ul class="nav navbar-nav navbar-left">
            <li>
                <%= link_to  "CreatePost", new_post_path %>
            </li>
        </ul>
    </nav>
      <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <div class="container">
        <%= yield %>
    </div>



</body>

</html>

app/views/pages/about.html.erb
<h1>
    <%= @title%>
</h1>
<h3>
    <%=@Desc%>
</h3>

app/views/posts/edit.html.erb
<div class="raw">

    <h1>Edit
        <%=@post.title%>
    </h1>

    <%= form_for :post,url: post_path(@post),method: :patch do |f| %>
        <% if @post.errors.any? %>
            <% @post.errors.full_messages.each do |msg| %>
                <div class="alert alert-danger">
                    <%= msg  %>
                </div>
                <% end %>

                    <% end %>
                        <p>

                            <%= f.label :title %>
                                <%= f.text_field(:title,{:class=>'form-control'}) %>

                        </p>

                        <p>
                            <%= f.label :body %>
                                <%= f.text_area(:body ,{:class=>'form-control'})%>
                        </p>
                        <br>
                        <p>
                            <%= f.submit({:class=>'btn btn-primary',:value=>'Update'}) %>
                        </p>

                        <% end %>
</div>

app/views/posts/index.html.erb
<br>
<br>
<h2>
    Blog Posts</h2>


<% @posts.each do |post| %>
    <div class="card">
        <h5 class="card-header">
            <%= post.title  %>
        </h5>
        <div class="card-body">

            <p class="card-text">
                <%= post.body  %>
            </p>
            <%= link_to  "Read More", post_path(post),:class=>'btn btn-primary' %>
                <!--<a href="#" class="btn btn-primary">Go somewhere</a>-->
        </div>
    </div>

    <br>
    <br>

    <%end%>

app/views/posts/new.html.erb
<div class="raw">

    <h1>Add Post</h1>

    <%= form_for :post,url: posts_path do |f| %>
        <% if @post.errors.any? %>
            <% @post.errors.full_messages.each do |msg| %>
                <div class="alert alert-danger">
                    <%= msg  %>
                </div>
                <% end %>

                    <% end %>
                        <p>

                            <%= f.label :title %>
                                <%= f.text_field(:title,{:class=>'form-control'}) %>


                        </p>

                        <p>
                            <%= f.label :body %>
                                <%= f.text_area(:body ,{:class=>'form-control'})%>
                        </p>
                        <br>
                        <p>
                            <%= f.submit({:class=>'btn btn-primary'}) %>
                        </p>

                        <% end %>
</div>

app/views/posts/show.html.erb
<br>
<br>
<br>


<div class="card">
    <h5 class="card-header">
        <%= @post.title%>
    </h5>

    <div class="card-body">

        <p class="card-text">
            <%= @post.body%>

        </p>
      <% if can? :update, @post%>  <%= link_to  "Edit", edit_post_path(@post),:class=>'btn btn-primary' %><%end%>
        <% if can? :destroy, @post%>    <%= link_to  "Delete", post_path,
                    method: :Delete,
                    data: {confirm: 'Are you sure ?'},
                    :class=>'btn btn-danger' %><%end%>

    </div>
    <hr>
    <%= render  "comments/comments" %>
        <br>
        <br>

        <%= render  "comments/form" %>